
# GetAll
# Consultar os clientes cadastrados
GET http://localhost:3000/client

###  
# Get by Id
# Consultar os produtos por Id
GET http://localhost:3000/product/5

###  
# Update a product by Id
# Atualizar um produto utilizando a Id
PUT http://localhost:3000/product/1
Content-Type: application/json

    {
        "product_name":"Notebook Dell",
        "product_desc":"Notebook Dell Inspiron 6578",
        "quantity":10,
        "price":2359
    }
  
###
# Create a client
# Criar um cliente
POST http://localhost:3000/client/
Content-Type: application/json

    {
        "nome":"Rafael da Silva",
        "email":"rafael@bol.com.br",
        "cidade":"Fpolis",
        "estado":"SC",
        "cep":"89990000"
    }
  
###
# Delete a produtc by Id
# Deletar um produto usando a Id
DELETE http://localhost:3000/product/8
