
# GetAll the clients
GET http://localhost:3000/client

###
# GetByCity
GET http://localhost:3000/client/cidade/fpolis


###  
# GetbyId
GET http://localhost:3000/client/5

###  
# Update a client using the Id
PUT http://localhost:3000/client/5
Content-Type: application/json

    {
        "nome":"Diogo Limera Silva",
        "email":"diogo@aol.com.br",
        "cidade":"Limeira",
        "estado":"SP",
        "cep":"06730000"
    }
  
###
# Create a client
POST http://localhost:3000/client/
Content-Type: application/json

    {
        "nome":"Maria Antonieta",
        "email":"maria@bol.com.br",
        "cidade":"Brasilia",
        "estado":"DF",
        "cep":"86490000"
    }
  


###
# Delete a client by Id
DELETE http://localhost:3000/client/2
