
# GetAll the clients
GET http://localhost:3000/client

###
# GetByCity
GET http://localhost:3000/client/cidade/fpolis


###  
# GetbyId
GET http://localhost:3000/client/7

###  
# Update a client using the Id
PUT http://localhost:3000/client/5
Content-Type: application/json

    {
        "nome":"Diogo Limera Silva",
        "email":"diogo@aol.com.br",
        "cidade":"Cuiaba",
        "estado":"MS",
        "cep":"06730000"
    }
  
###
# Create a client
POST http://localhost:3000/client/
Content-Type: application/json

    {
        "nome":"Arnaldo Antunes",
        "email":"arnaldo@bol.com.br",
        "cidade":"Curitiba",
        "estado":"PR",
        "cep":"86490000"
    }
  


###
# Delete a client by Id
DELETE http://localhost:3000/client/2
